/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */


public void port_click(GDropList source, GEvent event) {
  selectedPort = portList.getSelectedText();
  portSelected = true;
} 

public void done_click(GButton source, GEvent event) {}

public void record_click(GButton source, GEvent event) {

  try {

    jFileChooser = new JFileChooser();
    jFileChooser.setSelectedFile(new File("log.txt"));
    jFileChooser.showSaveDialog(null);
    String filePath = jFileChooser.getSelectedFile()+"";
    if ((filePath.equals("log.txt"))||(filePath.equals("null")))
    {
    } else
    {    
      record.setVisible(false);
      done.setVisible(true);
      logging = true;
      date = new Date();
      output = new FileWriter(jFileChooser.getSelectedFile(), true);
      bufferedWriter = new BufferedWriter(output);
      bufferedWriter.newLine();
      bufferedWriter.write(date+"");
      bufferedWriter.newLine();
      bufferedWriter.flush();
      bufferedWriter.close();
    }
  }
  catch(Exception e)
  {
  }
} 

public void close_click(GButton source, GEvent event) {
  exit();
}

public void start_click(GButton source, GEvent event) {
  start.setVisible(false);
  startPlot = true;
} 


public void imgButton1_click1(GImageButton source, GEvent event) {}



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("ces_view_ecg");
  portList = new GDropList(this, 5, 7, 200, 140, 3);
  portList.setItems(loadStrings("list_719422"), 0);
  portList.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  portList.addEventHandler(this, "port_click");
  done = new GButton(this, 395, 7, 100, 35);
  done.setText("DONE");
  done.setTextBold();
  done.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  done.addEventHandler(this, "done_click");
  record = new GButton(this, 395, 7, 100, 35);
  record.setText("RECORD");
  record.setTextBold();
  record.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  record.addEventHandler(this, "record_click");
  close = new GButton(this, 527, 7, 100, 35);
  close.setText("CLOSE");
  close.setTextBold();
  close.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  close.addEventHandler(this, "close_click");
  start = new GButton(this, 260, 7, 100, 35);
  start.setText("START");
  start.setTextBold();
  start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  start.addEventHandler(this, "start_click");
  imgButton1 = new GImageButton(this, 694, 446, 100, 30, new String[] { "logo.png", "logo.png", "logo.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  bpm1 = new GLabel(this, 620, 51, 139, 109);
  bpm1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  bpm1.setOpaque(false);
  SP02 = new GLabel(this, 620, 150, 139, 109);
  SP02.setOpaque(false);
  BP = new GLabel(this, 579, 252, 225, 107);
  BP.setOpaque(false);
  label1 = new GLabel(this, 579, 250, 75, 20);
  label1.setText("BP");
  label1.setTextBold();
  label1.setOpaque(false);
  label2 = new GLabel(this, 610, 150, 80, 19);
  label2.setText("SpO2      %");
  label2.setTextBold();
  label2.setOpaque(false);
  label3 = new GLabel(this, 604, 50, 74, 22);
  label3.setText("Heart Rate");
  label3.setTextBold();
  label3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label3.setOpaque(false);
  label4 = new GLabel(this, 736, 251, 80, 20);
  label4.setText("mmHg");
  label4.setTextBold();
  label4.setOpaque(false);
  label6 = new GLabel(this, 731, 51, 80, 20);
  label6.setText("bpm");
  label6.setTextBold();
  label6.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label6.setOpaque(false);
  Temp = new GLabel(this, 690, 350, 120, 106);
  Temp.setOpaque(false);
  label9 = new GLabel(this, 590, 350, 100, 20);
  label9.setText("Respiration");
  label9.setTextBold();
  label9.setOpaque(false);
  label5 = new GLabel(this, 634, 332, 64, 19);
  label5.setText("SYS");
  label5.setTextBold();
  label5.setOpaque(false);
  label7 = new GLabel(this, 698, 331, 28, 22);
  label7.setText("DIA");
  label7.setTextBold();
  label7.setOpaque(false);
  label8 = new GLabel(this, 682, 332, 15, 19);
  label8.setText("/");
  label8.setTextBold();
  label8.setOpaque(false);
  rpm = new GLabel(this, 580, 350, 120, 106);
  rpm.setOpaque(false);
  label11 = new GLabel(this, 696, 349, 80, 20);
  label11.setText("TEMP ( ° C)");
  label11.setTextBold();
  label11.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GDropList portList; 
GButton done; 
GButton record; 
GButton close; 
GButton start; 
GImageButton imgButton1; 
GLabel bpm1; 
GLabel SP02; 
GLabel BP; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label6; 
GLabel Temp; 
GLabel label9; 
GLabel label5; 
GLabel label7; 
GLabel label8; 
GLabel rpm; 
GLabel label11; 